{% set name = "optimum-habana" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimum-habana-{{ version }}.tar.gz
  sha256: 736ea38b461095ccf3cf1ca9a76b5aab619a3ea11ad1517631ef76a1d93d0016

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - datasets
    - optimum
    - pillow
    - scipy
    - sentencepiece
    - tokenizers
    - pytorch
    - transformers >=4.20.0

test:
  imports:
    - optimum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://huggingface.co/hardware/habana
  summary: |
    Optimum Habana is the interface between the Hugging Face Transformers library 
    and Habana Gaudi Processor (HPU). It provides a set of tools enabling easy model 
    loading and fine-tuning on single- and multi-HPU settings for different downstream tasks.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Optimum Habana is the interface between the Hugging Face Transformers library 
    and Habana Gaudi Processor (HPU). It provides a set of tools enabling easy model 
    loading and fine-tuning on single- and multi-HPU settings for different downstream tasks.

    PyPI: [https://pypi.org/project/optimum-habana/](https://pypi.org/project/optimum-habana/)

  doc_url: https://huggingface.co/hardware/habana
  dev_url: https://github.com/huggingface/optimum-habana

extra:
  recipe-maintainers:
    - sugatoray
